# Use a base image suitable for your app (e.g., Node.js)
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install app dependencies
RUN npm install
RUN npm install ts-node-dev

# Copy the rest of the app source code
COPY . .

# Expose the port on which the app listens
EXPOSE 3000

# Start the app when the container starts
CMD [ "npm", "start" ]
